execute as @a[scores={reset=1..}] run tag @s remove level1
execute as @a[scores={reset=1..}] run tag @s remove level2
execute as @a[scores={reset=1..}] run tag @s remove level3
execute as @a[scores={reset=1..}] run tag @s remove level4
execute as @a[scores={reset=1..}] run tag @s remove level5
execute as @a[scores={reset=1..}] run tag @s remove level6
execute as @a[scores={reset=1..}] run tag @s remove level7
execute as @a[scores={reset=1..}] run tag @s remove level8
execute as @a[scores={reset=1..}] run tag @s remove level9
execute as @a[scores={reset=1..}] run tag @s remove level10
execute as @a[scores={reset=1..}] run tag @s remove level11
execute as @a[scores={reset=1..}] run tag @s remove level12
execute as @a[scores={reset=1..}] run tag @s remove level13
execute as @a[scores={reset=1..}] run tag @s remove level14
execute as @a[scores={reset=1..}] run tag @s remove level15
execute as @a[scores={reset=1..}] run tag @s remove level16
execute as @a[scores={reset=1..}] run tag @s remove level17
execute as @a[scores={reset=1..}] run tag @s remove level18
