#
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s unless entity @e[type=player,team=blue,distance=..24] unless entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,distance=..24] run tag @s[tag=!move] add move
#
execute as @e[type=wolf,team=red] at @s unless entity @e[type=player,team=blue,distance=..24] unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,distance=..24] run tag @s[tag=move] remove move
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s unless entity @e[type=player,team=blue,distance=..24] unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..12] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red] at @s unless entity @e[type=player,team=blue,distance=..24] if entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,distance=..24] run tag @s[tag=move] remove move
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s unless entity @e[type=player,team=blue,distance=..24] if entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,distance=..24] run data modify entity @s AngryAt set from entity @e[type=wolf,team=blue,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red] at @s unless entity @e[type=player,team=blue,distance=..24] if entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,distance=..24] run tag @s[tag=move] remove move
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s unless entity @e[type=player,team=blue,distance=..24] if entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,distance=..24] run data modify entity @s AngryAt set from entity @e[type=wolf,team=blue,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red] at @s if entity @e[type=player,team=blue,distance=..24] unless entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,distance=..24] run tag @s[tag=move] remove move
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s if entity @e[type=player,team=blue,distance=..24] unless entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,distance=..24] run data modify entity @s AngryAt set from entity @e[type=player,team=blue,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red] at @s if entity @e[type=player,team=blue,distance=..24] unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,distance=..24] run tag @s[tag=move] remove move
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s if entity @e[type=player,team=blue,distance=..24] unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..12] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red] at @s if entity @e[type=player,team=blue,distance=..24] if entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,distance=..24] run tag @s[tag=move] remove move
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s if entity @e[type=player,team=blue,distance=..24] if entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,distance=..24] run data modify entity @s AngryAt set from entity @e[type=wolf,team=blue,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red] at @s if entity @e[type=player,team=blue,distance=..24] if entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,distance=..24] run tag @s[tag=move] remove move
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s if entity @e[type=player,team=blue,distance=..24] if entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,distance=..24] run data modify entity @s AngryAt set from entity @e[type=wolf,team=blue,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red,tag=red_min_bot,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,limit=1,sort=nearest] UUID
execute as @e[type=wolf,team=red,tag=red_min_bot,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,limit=1,sort=nearest] UUID
execute as @e[type=wolf,team=red,tag=red_min_bot,nbt={AngerTime:0}] at @s unless entity @e[type=player,team=blue,distance=..24] unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_top_4,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red,tag=red_min_mid,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,limit=1,sort=nearest] UUID
execute as @e[type=wolf,team=red,tag=red_min_mid,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,limit=1,sort=nearest] UUID
execute as @e[type=wolf,team=red,tag=red_min_mid,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_top_4,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red,tag=red_min_top,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_top_4,limit=1,sort=nearest] UUID
execute as @e[type=wolf,team=red,tag=red_min_top,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,limit=1,sort=nearest] UUID
execute as @e[type=wolf,team=red,tag=red_min_top,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_tr_top_4,limit=1,sort=nearest] UUID
#
execute as @e[type=wolf,team=red,nbt={AngerTime:0}] at @s unless entity @e[type=wolf,team=blue,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_tr_top_4,distance=..24] unless entity @e[type=shulker,team=blue,tag=blue_tr_bot_4,distance=..24] if entity @e[type=shulker,team=blue,tag=blue_nexus,distance=..24] run data modify entity @s AngryAt set from entity @e[type=shulker,team=blue,tag=blue_nexus,limit=1,sort=nearest] UUID
#
#execute as @e[type=wolf,team=red] at @s if entity @e[type=wolf,team=red,distance=0.01..0.7] unless entity @e[type=shulker,team=blue,distance=..5] unless entity @e[type=wolf,team=blue,distance=..5] run spreadplayers ~ ~ 1 1 false @s
execute if entity @e[type=polar_bear,team=red] run function lol:red_min_all_ai_super
