#
execute if entity @e[scores={game_timer=1..3600}] run summon wolf 205 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:20f,Tags:["red_min_bot","path_111","move"],CustomName:'{"text":"레드팀 바텀 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:20},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:4},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=1..3600}] run summon wolf 181 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:20f,Tags:["red_min_mid","path_121","move"],CustomName:'{"text":"레드팀 미드 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:20},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:4},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=1..3600}] run summon wolf 181 12 187 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:20f,Tags:["red_min_top","path_131","move"],CustomName:'{"text":"레드팀 탑 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:20},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:4},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
#
execute if entity @e[scores={game_timer=3601..7200}] run summon wolf 205 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:25f,Tags:["red_min_bot","path_111","move"],CustomName:'{"text":"레드팀 바텀 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:25},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=3601..7200}] run summon wolf 181 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:25f,Tags:["red_min_mid","path_121","move"],CustomName:'{"text":"레드팀 미드 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:25},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=3601..7200}] run summon wolf 181 12 187 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:25f,Tags:["red_min_top","path_131","move"],CustomName:'{"text":"레드팀 탑 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:25},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
#
execute if entity @e[scores={game_timer=7201..10800}] run summon wolf 205 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:30f,Tags:["red_min_bot","path_111","move"],CustomName:'{"text":"레드팀 바텀 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=7201..10800}] run summon wolf 181 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:30f,Tags:["red_min_mid","path_121","move"],CustomName:'{"text":"레드팀 미드 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=7201..10800}] run summon wolf 181 12 187 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:30f,Tags:["red_min_top","path_131","move"],CustomName:'{"text":"레드팀 탑 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
#
execute if entity @e[scores={game_timer=10801..14400}] run summon wolf 205 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:35f,Tags:["red_min_bot","path_111","move"],CustomName:'{"text":"레드팀 바텀 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:35},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=10801..14400}] run summon wolf 181 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:35f,Tags:["red_min_mid","path_121","move"],CustomName:'{"text":"레드팀 미드 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:35},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=10801..14400}] run summon wolf 181 12 187 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:35f,Tags:["red_min_top","path_131","move"],CustomName:'{"text":"레드팀 탑 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:35},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
#
execute if entity @e[scores={game_timer=14401..18000}] run summon wolf 205 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:40f,Tags:["red_min_bot","path_111","move"],CustomName:'{"text":"레드팀 바텀 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:40},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=14401..18000}] run summon wolf 181 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:40f,Tags:["red_min_mid","path_121","move"],CustomName:'{"text":"레드팀 미드 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:40},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=14401..18000}] run summon wolf 181 12 187 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:40f,Tags:["red_min_top","path_131","move"],CustomName:'{"text":"레드팀 탑 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:40},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
#
execute if entity @e[scores={game_timer=18001..}] run summon wolf 205 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:45f,Tags:["red_min_bot","path_111","move"],CustomName:'{"text":"레드팀 바텀 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:45},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:9},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=18001..}] run summon wolf 181 12 163 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:45f,Tags:["red_min_mid","path_121","move"],CustomName:'{"text":"레드팀 미드 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:45},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:9},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=18001..}] run summon wolf 181 12 187 {OnGround:1b,CustomNameVisible:1b,Team:"red",PersistenceRequired:1b,Health:45f,Tags:["red_min_top","path_131","move"],CustomName:'{"text":"레드팀 탑 미니언","color":"red"}',Attributes:[{Name:generic.max_health,Base:45},{Name:generic.follow_range,Base:27},{Name:generic.knockback_resistance,Base:0},{Name:generic.attack_damage,Base:9},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
