execute unless entity @e[type=armor_stand,tag=jg_red_slime_timer] run summon armor_stand 970 7 1040 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_red_slime_timer"],CustomName:'{"text":"jg_red_slime_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_red_silverfish_timer] run summon armor_stand 971 7 1040 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_red_silverfish_timer"],CustomName:'{"text":"jg_red_silverfish_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_red_panda_timer] run summon armor_stand 972 7 1040 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_red_panda_timer"],CustomName:'{"text":"jg_red_panda_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_red_piglin_timer] run summon armor_stand 973 7 1040 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_red_piglin_timer"],CustomName:'{"text":"jg_red_piglin_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_red_golem_timer] run summon armor_stand 974 7 1040 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_red_golem_timer"],CustomName:'{"text":"jg_red_golem_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_red_bee_timer] run summon armor_stand 975 7 1040 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_red_bee_timer"],CustomName:'{"text":"jg_red_bee_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_red_axolotl_timer] run summon armor_stand 976 7 1040 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_red_axolotl_timer"],CustomName:'{"text":"jg_red_axolotl_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_dragon_timer] run summon armor_stand 977 7 1040 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_dragon_timer"],CustomName:'{"text":"jg_dragon_timer"}'}
#
execute unless entity @e[type=armor_stand,tag=jg_blue_slime_timer] run summon armor_stand 970 7 1045 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_blue_slime_timer"],CustomName:'{"text":"jg_blue_slime_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_blue_silverfish_timer] run summon armor_stand 971 7 1045 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_blue_silverfish_timer"],CustomName:'{"text":"jg_blue_silverfish_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_blue_panda_timer] run summon armor_stand 972 7 1045 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_blue_panda_timer"],CustomName:'{"text":"jg_blue_panda_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_blue_piglin_timer] run summon armor_stand 973 7 1045 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_blue_piglin_timer"],CustomName:'{"text":"jg_blue_piglin_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_blue_golem_timer] run summon armor_stand 974 7 1045 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_blue_golem_timer"],CustomName:'{"text":"jg_blue_golem_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_blue_bee_timer] run summon armor_stand 975 7 1045 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_blue_bee_timer"],CustomName:'{"text":"jg_blue_bee_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_blue_axolotl_timer] run summon armor_stand 976 7 1045 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_blue_axolotl_timer"],CustomName:'{"text":"jg_blue_axolotl_timer"}'}
execute unless entity @e[type=armor_stand,tag=jg_wither_timer] run summon armor_stand 977 7 1045 {CustomNameVisible:1b,Invulnerable:1b,PersistenceRequired:1b,Tags:["jg_wither_timer"],CustomName:'{"text":"jg_wither_timer"}'}
