execute if entity @e[scores={game_timer=1..3600}] run summon panda 73 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:40f,Age:0,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:40},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=3601..7200}] run summon panda 73 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:50f,Age:0,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:50},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=7201..10800}] run summon panda 73 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:60f,Age:0,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:60},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:10},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=10801..14400}] run summon panda 73 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:70f,Age:0,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:70},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:12},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=14401..18000}] run summon panda 73 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:80f,Age:0,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:80},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:14},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=18001..}] run summon panda 73 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:90f,Age:0,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:90},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:16},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=1..3600}] run summon panda 73 11 9 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:20f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:20},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:3},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=3601..7200}] run summon panda 73 11 9 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:25f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:25},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:4},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=7201..10800}] run summon panda 73 11 9 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:30f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=10801..14400}] run summon panda 73 11 9 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:35f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:35},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=14401..18000}] run summon panda 73 11 9 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:40f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:40},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=18001..}] run summon panda 73 11 9 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:45f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:45},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=1..3600}] run summon panda 75 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:20f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:20},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:3},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=3601..7200}] run summon panda 75 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:25f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:25},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:4},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=7201..10800}] run summon panda 75 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:30f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=10801..14400}] run summon panda 75 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:35f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:35},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=14401..18000}] run summon panda 75 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:40f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:40},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=18001..}] run summon panda 75 11 7 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:45f,Age:-999999,MainGene:"aggressive",HiddenGene:"normal",Tags:["jg_blue_panda"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"아기 판다","color":"#018000"}]',Attributes:[{Name:generic.knockback_resistance,Base:0.7},{Name:generic.max_health,Base:45},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
