function lol:jg/summon_jg_red_slime
function lol:jg/summon_jg_red_silverfish
function lol:jg/summon_jg_red_panda
function lol:jg/summon_jg_red_piglin
function lol:jg/summon_jg_red_golem
function lol:jg/summon_jg_red_bee
function lol:jg/summon_jg_red_axolotl
function lol:jg/summon_jg_blue_slime
function lol:jg/summon_jg_blue_silverfish
function lol:jg/summon_jg_blue_panda
function lol:jg/summon_jg_blue_piglin
function lol:jg/summon_jg_blue_golem
function lol:jg/summon_jg_blue_bee
function lol:jg/summon_jg_blue_axolotl