execute if entity @e[scores={game_timer=1..3600}] run summon slime 3 15 91 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:40f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:40},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=3601..7200}] run summon slime 3 15 91 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:50f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:50},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=7201..10800}] run summon slime 3 15 91 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:60f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:60},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:10},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=10801..14400}] run summon slime 3 15 91 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:70f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:70},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:12},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=14401..18000}] run summon slime 3 15 91 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:80f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:80},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:14},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=18001..}] run summon slime 3 15 91 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:90f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:90},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:16},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
#
execute if entity @e[scores={game_timer=1..3600}] run summon slime 3 15 87 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:30f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=3601..7200}] run summon slime 3 15 87 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:37f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=7201..10800}] run summon slime 3 15 87 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:44f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=10801..14400}] run summon slime 3 15 87 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:51f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=14401..18000}] run summon slime 3 15 87 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:58f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:9},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=18001..}] run summon slime 3 15 87 {CustomNameVisible:1b,DeathTime:19,Team:"jungle",PersistenceRequired:1b,Health:65f,Size:2,Tags:["jg_blue_slime"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"슬라임","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:30},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:10},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
