execute if entity @e[scores={game_timer=1..3600}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:25f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:25},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:4},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=3601..7200}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:31f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:31},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=7201..10800}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:37f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:37},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=10801..14400}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:43f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:43},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=14401..18000}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:49f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:49},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=18001..}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:55f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:55},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:9},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=1..3600}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:25f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:25},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:4},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=3601..7200}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:31f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:31},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=7201..10800}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:37f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:37},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=10801..14400}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:43f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:43},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=14401..18000}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:49f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:49},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=18001..}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:55f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:55},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:9},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
#
execute if entity @e[scores={game_timer=1..3600}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:25f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:25},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:4},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=3601..7200}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:31f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:31},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=7201..10800}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:37f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:37},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=10801..14400}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:43f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:43},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:7},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=14401..18000}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:49f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:49},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:8},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
execute if entity @e[scores={game_timer=18001..}] run summon bee 123 11 74 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:55f,Tags:["jg_red_bee"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"꿀벌","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:55},{Name:generic.follow_range,Base:5},{Name:generic.attack_damage,Base:9},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
