execute if entity @e[scores={game_timer=1..3600}] run summon axolotl 130 10 17 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:60f,Variant:4,Tags:["jg_red_axolotl"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"물짱이","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:60},{Name:generic.knockback_resistance,Base:0.9},{Name:generic.movement_speed,Base:5.5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}

execute if entity @e[scores={game_timer=3601..7200}] run summon axolotl 130 10 17 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:75f,Variant:4,Tags:["jg_red_axolotl"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"물짱이","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:75},{Name:generic.knockback_resistance,Base:0.9},{Name:generic.movement_speed,Base:5.5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}

execute if entity @e[scores={game_timer=7201..10800}] run summon axolotl 130 10 17 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:90f,Variant:4,Tags:["jg_red_axolotl"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"물짱이","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:90},{Name:generic.knockback_resistance,Base:0.9},{Name:generic.movement_speed,Base:5.5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}

execute if entity @e[scores={game_timer=10801..14400}] run summon axolotl 130 10 17 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:105f,Variant:4,Tags:["jg_red_axolotl"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"물짱이","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:105},{Name:generic.knockback_resistance,Base:0.9},{Name:generic.movement_speed,Base:5.5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}

execute if entity @e[scores={game_timer=14401..18000}] run summon axolotl 130 10 17 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:120f,Variant:4,Tags:["jg_red_axolotl"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"물짱이","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:120},{Name:generic.knockback_resistance,Base:0.9},{Name:generic.movement_speed,Base:5.5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}

execute if entity @e[scores={game_timer=18001..21600}] run summon axolotl 130 10 17 {CustomNameVisible:1b,Team:"jungle",PersistenceRequired:1b,Health:135f,Variant:4,Tags:["jg_red_axolotl"],CustomName:'[{"text":"정글 ","color":"#8C3000"},{"text":"물짱이","color":"#018000"}]',Attributes:[{Name:generic.max_health,Base:135},{Name:generic.knockback_resistance,Base:0.9},{Name:generic.movement_speed,Base:5.5},{Name:generic.armor,Base:0},{Name:generic.armor_toughness,Base:0}]}
